import React from 'react'


  export const offer = [
    {
      id: 1,
      category: "flight",
      badge: "FLIGHT",
      badge_Type: "",
      expiry: "2025-12-31",
      popularity: 124,
      Total_savings: 4000,
      image: "../img/img6.avif",
      title: "Early Bird Flight Discount",
      description: "Book your flights 30 days in advance and get 20% off on domestic routes.",
      original_Price: 15999,
      discount_Price: 11999,
      progress: null
    },
    {
      id: 2,
      category: "flight",
      badge: "HOT DEAL",
      badge_Type: "hot-deal",
      expiry_Date: "2025-11-15",
      popularity: 89,
      Total_savings: 3200,
      image: "",
      title: "Business Class Upgrade",
      description: "Get 40% off on business class upgrades for international flights. Limited seats!",
      original_Price: 8000,
      discount_Price: 4800,
      progress: 75
    },
    {
      id: 3,
      category: "flight",
      badge: "FLIGHT",
      badge_Type: "",
      expiry: "2025-11-20",
      popularity: 156,
      Total_savings: 1625,
      image: "",
      title: "Weekend Getaway Flights",
      description: "Special weekend flight deals with 25% off on select routes. Perfect for short trips!",
      original_Price: 6500,
      discount_Price: 4875,
      progress: null
    },
    {
      id: 4,
      category: "flight",
      badge: "FLIGHT",
      badge_Type: "",
      expiry: "2025-12-25",
      popularity: 78,
      Total_savings: 1800,
      image: "../img/img5.avif",
      title: "Family Flight Package",
      description: "Travel with family and get 15% off for each additional passenger. Kids fly at 50% off.",
      original_Price: 12000,
      discount_Price: 10200,
      progress: null
    },
    {
      id: 5,
      category: "flight",
      badge: "LAST CHANCE",
      badge_Type: "last-chance",
      expiry: "2025-09-30",
      popularity: 203,
      Total_savings: 2400,
      image: "../img/FlightImage1.avif",
      title: "Last Minute Flight Deals",
      description: "Up to 30% off on last minute flight bookings. Perfect for spontaneous travelers!",
      original_Price: 8000,
      discount_Price: 5600,
      progress: null
    },
    {
      id: 6,
      category: "flight",
      badge: "FLIGHT",
      badge_Type: "",
      expiry: "2026-03-31",
      popularity: 145,
      Total_savings: 1500,
      image: "",
      title: "Student Flight Discount",
      description: "Special 25% discount for students with valid ID. Available on all domestic routes.",
      original_Price: 6000,
      discount_Price: 4500,
      progress: null
    },
    {
      id: 7,
      category: "flight",
      badge: "FLIGHT",
      badge_Type: "",
      expiry: "2025-10-15",
      popularity: 167,
      Total_savings: 2200,
      image: "",
      title: "Senior Citizen Flight Offer",
      description: "Special 30% discount for senior citizens on all domestic flights.",
      original_Price: 11000,
      discount_Price: 7700,
      progress: null
    },
    {
      id: 8,
      category: "flight",
      badge: "EXCLUSIVE",
      badge_Type: "exclusive",
      expiry: "2025-11-30",
      popularity: 134,
      Total_savings: 5000,
      image: "",
      title: "International Flight Sale",
      description: "Up to 40% off on international flights to popular destinations.",
      original_Price: 25000,
      discount_Price: 15000,
      progress: null
    },
    {
      id: 9,
      category: "flight",
      badge: "FLIGHT",
      badge_Type: "",
      expiry: "2025-12-20",
      popularity: 189,
      Total_savings: 1800,
      image: "",
      title: "Early Morning Flight Deal",
      description: "25% off on early morning flights. Perfect for business travelers!",
      original_Price: 7200,
      discount_Price: 5400,
      progress: null
    },
    {
      id: 10,
      category: "flight",
      badge: "HOT DEAL",
      badge_Type: "hot-deal",
      expiry: "2025-10-31",
      popularity: 223,
      Total_savings: 3000,
      image: "",
      title: "Festival Season Flights",
      description: "Special festival discounts on all major routes. Book early!",
      original_Price: 15000,
      discount_Price: 12000,
      progress: 60
    },
    {
      id: 11,
      category: "flight",
      badge: "FLIGHT",
      badge_Type: "",
      expiry: "2026-01-15",
      popularity: 98,
      Total_savings: 1200,
      image: "",
      title: "Round Trip Special",
      description: "Get 20% off on round trip bookings to hill stations.",
      original_Price: 6000,
      discount_Price: 4800,
      progress: null
    },
    {
      id: 12,
      category: "flight",
      badge: "FLIGHT",
      badge_Type: "",
      expiry: "2025-11-25",
      popularity: 145,
      Total_savings: 2500,
      image: "",
      title: "Monsoon Flight Offers",
      description: "Enjoy 25% off on flights during monsoon season to beach destinations.",
      original_Price: 10000,
      discount_Price: 7500,
      progress: null
    },
    {
      id: 13,
      category: "flight",
      badge: "LAST CHANCE",
      badge_Type: "last-chance",
      expiry: "2025-09-20",
      popularity: 178,
      Total_savings: 1800,
      image: "",
      title: "End of Season Sale",
      description: "Last chance to grab 30% off on summer destination flights.",
      original_Price: 6000,
      discount_Price: 4200,
      progress: null
    },
    {
      id: 14,
      category: "flight",
      badge: "FLIGHT",
      badge_Type: "",
      expiry: "2025-12-31",
      popularity: 112,
      Total_savings: 1600,
      image: "",
      title: "New Year Special Flights",
      description: "Book your New Year travel now and get 20% early bird discount.",
      original_Price: 8000,
      discount_Price: 6400,
      progress: null
    },
    {
      id: 15,
      category: "flight",
      badge: "EXCLUSIVE",
      badge_Type: "exclusive",
      expiry: "2025-10-10",
      popularity: 156,
      Total_savings: 3500,
      image: "",
      title: "Premium Economy Launch",
      description: "Special introductory offer on premium economy class seats.",
      original_Price: 17500,
      discount_Price: 14000,
      progress: 45
    },

    // Hotel Offers
    {
      id: 16,
      category: "hotel",
      badge: "HOTEL",
      badge_Type: "",
      expiry: "2025-12-29",
      popularity: 156,
      Total_savings: 2500,
      image: "../img/img4.avif",
      title: "Weekend Hotel Getaway",
      description: "Get 25% off on hotel bookings for Friday-Sunday stays. Free breakfast included.",
      original_Price: 10000,
      discount_Price: 7500,
      progress: null
    },
    {
      id: 17,
      category: "hotel",
      badge: "EXCLUSIVE",
      badge_Type: "exclusive",
      expiry: "2025-11-20",
      popularity: 67,
      Total_savings: 4200,
      image: "../img/img3.avif",
      title: "Luxury Resort Deal",
      description: "5-star luxury resorts at 35% discount. Includes spa access and complimentary dinner.",
      original_Price: 12000,
      discount_Price: 7800,
      progress: null
    },
    {
      id: 18,
      category: "hotel",
      badge: "HOTEL",
      badge_Type: "",
      expiry: "2025-10-30",
      popularity: 98,
      Total_savings: 1800,
      image: "../img/photo-1542314831-068cd1dbfeeb.jpeg",
      title: "Extended Stay Discount",
      description: "Stay 5 nights or more and get 30% off. Perfect for long vacations or work trips.",
      original_Price: 6000,
      discount_Price: 4200,
      progress: null
    },
    {
      id: 19,
      category: "hotel",
      badge: "HOTEL",
      badge_Type: "",
      expiry: "2025-12-15",
      popularity: 112,
      Total_savings: 2200,
      image: "../img/img2avif.avif",
      title: "Business Hotel Special",
      description: "20% off on business hotels with complimentary Wi-Fi and breakfast. Free cancellation.",
      original_Price: 11000,
      discount_Price: 8800,
      progress: null
    },
    {
      id: 20,
      category: "hotel",
      badge: "HOT DEAL",
      badge_Type: "hot-deal",
      expiry: "2025-10-31",
      popularity: 134,
      Total_savings: 3200,
      image: "../img/img1.avif",
      title: "Beach Resort Package",
      description: "Beachfront resorts at 40% off. Includes water sports and daily buffet meals.",
      original_Price: 8000,
      discount_Price: 4800,
      progress: null
    },
    {
      id: 21,
      category: "hotel",
      badge: "LAST CHANCE",
      badge_Type: "last-chance",
      expiry: "2025-09-25",
      popularity: 89,
      Total_savings: 1500,
      image: "../img/img7.avif",
      title: "Last Minute Hotel Deal",
      description: "Up to 50% off on same-day hotel bookings. Available in major cities nationwide.",
      original_Price: 3000,
      discount_Price: 1500,
      progress: null
    },
    {
      id: 22,
      category: "hotel",
      badge: "HOTEL",
      badge_Type: "",
      expiry: "2025-11-30",
      popularity: 145,
      Total_savings: 2000,
      image: "",
      title: "Heritage Hotel Experience",
      description: "Stay at heritage properties and get 25% off with cultural activities included.",
      original_Price: 8000,
      discount_Price: 6000,
      progress: null
    },
    {
      id: 23,
      category: "hotel",
      badge: "EXCLUSIVE",
      badge_Type: "exclusive",
      expiry: "2025-12-10",
      popularity: 78,
      Total_savings: 4500,
      image: "",
      title: "Wildlife Resort Package",
      description: "Jungle resorts with safari included at 35% discount. Perfect for nature lovers!",
      original_Price: 15000,
      discount_Price: 10500,
      progress: null
    },

    // Bus Offers
    {
      id: 24,
      category: "bus",
      badge: "BUS",
      badge_Type: "",
      expiry: "2026-01-21",
      popularity: 178,
      Total_savings: 500,
      image: "../img/img8.avif",
      title: "Bus Bonanza Week",
      description: "Enjoy flat 25% off on all bus bookings made this week. Use code: BUS20",
      original_Price: 2000,
      discount_Price: 1500,
      progress: null
    },
    {
      id: 25,
      category: "bus",
      badge: "BUS",
      badge_Type: "",
      expiry: "2025-08-31",
      popularity: 234,
      Total_savings: 400,
      image: "../img/img9.avif",
      title: "Student Travel Pass",
      description: "Special 40% discount for students on all bus routes. Valid student ID required.",
      original_Price: 1000,
      discount_Price: 600,
      progress: null
    },
    {
      id: 26,
      category: "bus",
      badge: "BUS",
      badge_Type: "",
      expiry: "2025-11-15",
      popularity: 145,
      Total_savings: 750,
      image: "../img/img10.avif",
      title: "Group Travel Discount",
      description: "Travel with 4 or more people and get 30% off on bus tickets. Perfect for group trips!",
      original_Price: 2500,
      discount_Price: 1750,
      progress: null
    },
    {
      id: 27,
      category: "bus",
      badge: "BUS",
      badge_Type: "",
      expiry: "2025-12-31",
      popularity: 89,
      Total_savings: 600,
      image: "../img/img8.avif",
      title: "Luxury Bus Experience",
      description: "20% off on luxury bus services with extra legroom, Wi-Fi, and entertainment.",
      original_Price: 3000,
      discount_Price: 2400,
      progress: null
    },
    {
      id: 28,
      category: "bus",
      badge: "HOT DEAL",
      badge_Type: "hot-deal",
      expiry: "2025-10-28",
      popularity: 167,
      Total_savings: 525,
      image: "../img/img9.avif",
      title: "Early Morning Special",
      description: "35% off on early morning bus departures (before 7 AM). Start your journey with Total_savings!",
      original_Price: 1500,
      discount_Price: 975,
      progress: null
    },
    {
      id: 29,
      category: "bus",
      badge: "BUS",
      badge_Type: "",
      expiry: "2025-11-30",
      popularity: 98,
      Total_savings: 400,
      image: "../img/img8.avif",
      title: "Weekend Bus Getaway",
      description: "25% off on weekend bus travel. Explore nearby destinations without breaking the bank.",
      original_Price: 1600,
      discount_Price: 1200,
      progress: null
    },

    // Train Offers
    {
      id: 30,
      category: "train",
      badge: "TRAIN",
      badge_Type: "",
      expiry: "2025-11-21",
      popularity: 189,
      Total_savings: 800,
      image: "",
      title: "Railway Rewards",
      description: "Book AC train tickets and get 10% cashback plus free cancellation.",
      original_Price: 8000,
      discount_Price: 7200,
      progress: null
    },
    {
      id: 31,
      category: "train",
      badge: "TRAIN",
      badge_Type: "",
      expiry: "2026-02-28",
      popularity: 156,
      Total_savings: 1200,
      image: "../img/img11.avif",
      title: "Monsoon Special Trains",
      description: "15% discount on all train bookings during monsoon season. Perfect for rainy getaways!",
      original_Price: 8000,
      discount_Price: 6800,
      progress: null
    },
    {
      id: 32,
      category: "train",
      badge: "EXCLUSIVE",
      badge_Type: "exclusive",
      expiry: "2025-12-25",
      popularity: 134,
      Total_savings: 1500,
      image: "",
      title: "First Class Upgrade",
      description: "Upgrade to first class at 25% discount. Limited seats available on premium routes.",
      original_Price: 6000,
      discount_Price: 4500,
      progress: null
    },
    {
      id: 33,
      category: "train",
      badge: "TRAIN",
      badge_Type: "",
      expiry: "2025-10-15",
      popularity: 178,
      Total_savings: 600,
      image: "../img/img11.avif",
      title: "Group Train Booking",
      description: "Book for 6+ passengers and get 20% off on all train classes. Perfect for family trips!",
      original_Price: 3000,
      discount_Price: 2400,
      progress: null
    },
    {
      id: 34,
      category: "train",
      badge: "HOT DEAL",
      badge_Type: "hot-deal",
      expiry: "2025-11-20",
      popularity: 112,
      Total_savings: 900,
      image: "",
      title: "Festival Special Trains",
      description: "Special 15% discount on festival season trains. Book early to avoid last-minute rush!",
      original_Price: 6000,
      discount_Price: 5100,
      progress: null
    },
    {
      id: 35,
      category: "train",
      badge: "TRAIN",
      badge_Type: "",
      expiry: "2025-12-31",
      popularity: 145,
      Total_savings: 700,
      image: "../img/img11.avif",
      title: "Student Rail Pass",
      description: "Special 25% discount for students on all train routes. Valid student ID required.",
      original_Price: 2800,
      discount_Price: 2100,
      progress: null
    },

    // Cab Offers 
    {
      id: 36,
      category: "cab",
      badge: "CAB",
      badge_Type: "",
      expiry: "2025-12-10",
      popularity: 267,
      Total_savings: 100,
      image: "../img/img12.avif",
      title: "Car Ride Discount",
      description: "Get flat ₹100 off on your first cab ride. Applicable in all major cities.",
      original_Price: 500,
      discount_Price: 400,
      progress: null
    },
    {
      id: 37,
      category: "cab",
      badge: "CAB",
      badge_Type: "",
      expiry: "2025-11-15",
      popularity: 189,
      Total_savings: 150,
      image: "../img/img13.avif",
      title: "Airport Transfer Special",
      description: "30% off on airport transfers. Available 24/7 with premium vehicles.",
      original_Price: 500,
      discount_Price: 350,
      progress: null
    },
    {
      id: 38,
      category: "cab",
      badge: "HOT DEAL",
      badge_Type: "hot-deal",
      expiry: "2025-10-31",
      popularity: 156,
      Total_savings: 120,
      image: "../img/img14.avif",
      title: "Weekend Cab Special",
      description: "25% off on all cab rides during weekends. Explore your city in comfort and style!",
      original_Price: 480,
      discount_Price: 360,
      progress: null
    },
    {
      id: 39,
      category: "cab",
      badge: "CAB",
      badge_Type: "",
      expiry: "2026-04-25",
      popularity: 134,
      Total_savings: 200,
      image: "../img/img15.avif",
      title: "Outstation Cab Discount",
      description: "20% off on outstation cab bookings. Perfect for weekend getaways and road trips.",
      original_Price: 1000,
      discount_Price: 800,
      progress: null
    },
    {
      id: 40,
      category: "cab",
      badge: "LAST CHANCE",
      badge_Type: "last-chance",
      expiry: "2026-01-30",
      popularity: 178,
      Total_savings: 80,
      image: "../img/img16.avif",
      title: "Ride Sharing Bonus",
      description: "Share your ride and get 20% off. Perfect for office commutes and group travel.",
      original_Price: 400,
      discount_Price: 320,
      progress: null
    }
  ];

