import React from "react";

export const offersData = [
    
    {
        id: 'flight-1',
        category: 'flight',
        expiry: '2025-12-31',
        popularity: 124,
        savings: 4000,
        badge: 'FLIGHT',
        image: '../img/img6.avif',
        title: 'Early Bird Flight Discount',
        description: 'Book your flights 30 days in advance and get 20% off on domestic routes.',
        originalPrice: '₹15,999',
        discountedPrice: '₹11,999',
        progress: null
    },
    {
        id: 'flight-2',
        category: 'flight',
        expiry: '2025-11-15',
        popularity: 89,
        savings: 3200,
        badge: 'HOT DEAL',
        image: '',
        title: 'Business Class Upgrade',
        description: 'Get 40% off on business class upgrades for international flights. Limited seats!',
        originalPrice: '₹8,000',
        discountedPrice: '₹4,800',
        progress: 75
    },
   {
    id: 'flight-3',
    category: 'flight',
    expiry: '2025-11-20',
    popularity: 156,
    savings: 1625,  
    badge: 'FLIGHT',  
    image: '',
    title: 'Weekend Getaway Flights',  
    description: 'Special weekend flight deals with 25% off on select routes. Perfect for short trips!',
    originalPrice: '₹6,500',  
    discountedPrice: '₹4,875',
    progress: null  
},
    {
        id: 'flight-4',
        category: 'flight',
        expiry: '2025-12-25',
        popularity: 78,
        savings: 1800,
        badge: 'FLIGHT',
        image: '../img/img5.avif',
        title: 'Family Flight Package',
        description: 'Travel with family and get 15% off for each additional passenger. Kids fly at 50% off.',
        originalPrice: '₹12,000',
        discountedPrice: '₹10,200',
        progress: null
    },
    {
        id: 'flight-5',
        category: 'flight',
        expiry: '2025-09-30',
        popularity: 203,
        savings: 2400,
        badge: 'LAST CHANCE',
        image: '../img/FlightImage1.avif',
        title: 'Last Minute Flight Deals',
        description: 'Up to 30% off on last minute flight bookings. Perfect for spontaneous travelers!',
        originalPrice: '₹8,000',
        discountedPrice: '₹5,600',
        progress: null
    },
    {
        id: 'flight-6',
        category: 'flight',
        expiry: '2026-03-31',
        popularity: 145,
        savings: 1500,
        badge: 'FLIGHT',
        image: '',
        title: 'Student Flight Discount',
        description: 'Special 25% discount for students with valid ID. Available on all domestic routes.',
        originalPrice: '₹6,000',
        discountedPrice: '₹4,500',
        progress: null
    },

    // Hotel Offers (6 cards)
    {
        id: 'hotel-1',
        category: 'hotel',
        expiry: '2025-12-29',
        popularity: 156,
        savings: 2500,
        badge: 'HOTEL',
        image: '../img/img4.avif',
        title: 'Weekend Hotel Getaway',
        description: 'Get 25% off on hotel bookings for Friday-Sunday stays. Free breakfast included.',
        originalPrice: '₹10,000',
        discountedPrice: '₹7,500',
        progress: null
    },
    {
        id: 'hotel-2',
        category: 'hotel',
        expiry: '2025-11-20',
        popularity: 67,
        savings: 4200,
        badge: 'EXCLUSIVE',
        image: '../img/img3.avif',
        title: 'Luxury Resort Deal',
        description: '5-star luxury resorts at 35% discount. Includes spa access and complimentary dinner.',
        originalPrice: '₹12,000',
        discountedPrice: '₹7,800',
        progress: null
    },
    {
        id: 'hotel-3',
        category: 'hotel',
        expiry: '2025-10-30',
        popularity: 98,
        savings: 1800,
        badge: 'HOTEL',
        image: '../img/photo-1542314831-068cd1dbfeeb.jpeg',
        title: 'Extended Stay Discount',
        description: 'Stay 5 nights or more and get 30% off. Perfect for long vacations or work trips.',
        originalPrice: '₹6,000',
        discountedPrice: '₹4,200',
        progress: null
    },
    {
        id: 'hotel-4',
        category: 'hotel',
        expiry: '2025-12-15',
        popularity: 112,
        savings: 2200,
        badge: 'HOTEL',
        image: '../img/img2avif.avif',
        title: 'Business Hotel Special',
        description: '20% off on business hotels with complimentary Wi-Fi and breakfast. Free cancellation.',
        originalPrice: '₹11,000',
        discountedPrice: '₹8,800',
        progress: null
    },
    {
        id: 'hotel-5',
        category: 'hotel',
        expiry: '2025-10-31',
        popularity: 134,
        savings: 3200,
        badge: 'HOT DEAL',
        image: '../img/img1.avif',
        title: 'Beach Resort Package',
        description: 'Beachfront resorts at 40% off. Includes water sports and daily buffet meals.',
        originalPrice: '₹8,000',
        discountedPrice: '₹4,800',
        progress: null
    },
    {
        id: 'hotel-6',
        category: 'hotel',
        expiry: '2025-09-25',
        popularity: 89,
        savings: 1500,
        badge: 'LAST CHANCE',
        image: '../img/img7.avif',
        title: 'Last Minute Hotel Deal',
        description: 'Up to 50% off on same-day hotel bookings. Available in major cities nationwide.',
        originalPrice: '₹3,000',
        discountedPrice: '₹1,500',
        progress: null
    },

    // Bus Offers (6 cards)
    {
        id: 'bus-1',
        category: 'bus',
        expiry: '2026-01-21',
        popularity: 178,
        savings: 500,
        badge: 'BUS',
        image: '../img/img8.avif',
        title: 'Bus Bonanza Week',
        description: 'Enjoy flat 25% off on all bus bookings made this week. Use code: BUS20',
        originalPrice: '₹2,000',
        discountedPrice: '₹1,500',
        progress: null
    },
    {
        id: 'bus-2',
        category: 'bus',
        expiry: '2025-08-31',
        popularity: 234,
        savings: 400,
        badge: 'BUS',
        image: '../img/img9.avif',
        title: 'Student Travel Pass',
        description: 'Special 40% discount for students on all bus routes. Valid student ID required.',
        originalPrice: '₹1,000',
        discountedPrice: '₹600',
        progress: null
    },
    {
        id: 'bus-3',
        category: 'bus',
        expiry: '2025-11-15',
        popularity: 145,
        savings: 750,
        badge: 'BUS',
        image: '../img/img10.avif',
        title: 'Group Travel Discount',
        description: 'Travel with 4 or more people and get 30% off on bus tickets. Perfect for group trips!',
        originalPrice: '₹2,500',
        discountedPrice: '₹1,750',
        progress: null
    },
    {
        id: 'bus-4',
        category: 'bus',
        expiry: '2025-12-31',
        popularity: 89,
        savings: 600,
        badge: 'BUS',
        image: '../img/img8.avif',
        title: 'Luxury Bus Experience',
        description: '20% off on luxury bus services with extra legroom, Wi-Fi, and entertainment.',
        originalPrice: '₹3,000',
        discountedPrice: '₹2,400',
        progress: null
    },
    {
        id: 'bus-5',
        category: 'bus',
        expiry: '2025-10-28',
        popularity: 167,
        savings: 525,
        badge: 'HOT DEAL',
        image: '../img/img9.avif',
        title: 'Early Morning Special',
        description: '35% off on early morning bus departures (before 7 AM). Start your journey with savings!',
        originalPrice: '₹1,500',
        discountedPrice: '₹975',
        progress: null
    },
    {
        id: 'bus-6',
        category: 'bus',
        expiry: '2025-11-30',
        popularity: 98,
        savings: 400,
        badge: 'BUS',
        image: '../img/img8.avif',
        title: 'Weekend Bus Getaway',
        description: '25% off on weekend bus travel. Explore nearby destinations without breaking the bank.',
        originalPrice: '₹1,600',
        discountedPrice: '₹1,200',
        progress: null
    },

    // Train Offers (6 cards)
    {
        id: 'train-1',
        category: 'train',
        expiry: '2025-11-21',
        popularity: 189,
        savings: 800,
        badge: 'TRAIN',
        image: '',
        title: 'Railway Rewards',
        description: 'Book AC train tickets and get 10% cashback plus free cancellation.',
        originalPrice: '₹8,000',
        discountedPrice: '₹7,200',
        progress: null
    },
    {
        id: 'train-2',
        category: 'train',
        expiry: '2026-02-28',
        popularity: 156,
        savings: 1200,
        badge: 'TRAIN',
        image: '../img/img11.avif',
        title: 'Monsoon Special Trains',
        description: '15% discount on all train bookings during monsoon season. Perfect for rainy getaways!',
        originalPrice: '₹8,000',
        discountedPrice: '₹6,800',
        progress: null
    },
    {
        id: 'train-3',
        category: 'train',
        expiry: '2025-12-25',
        popularity: 134,
        savings: 1500,
        badge: 'EXCLUSIVE',
        image: '',
        title: 'First Class Upgrade',
        description: 'Upgrade to first class at 25% discount. Limited seats available on premium routes.',
        originalPrice: '₹6,000',
        discountedPrice: '₹4,500',
        progress: null
    },
    {
        id: 'train-4',
        category: 'train',
        expiry: '2025-10-15',
        popularity: 178,
        savings: 600,
        badge: 'TRAIN',
        image: '../img/img11.avif',
        title: 'Group Train Booking',
        description: 'Book for 6+ passengers and get 20% off on all train classes. Perfect for family trips!',
        originalPrice: '₹3,000',
        discountedPrice: '₹2,400',
        progress: null
    },
    {
        id: 'train-5',
        category: 'train',
        expiry: '2025-11-20',
        popularity: 112,
        savings: 900,
        badge: 'HOT DEAL',
        image: '',
        title: 'Festival Special Trains',
        description: 'Special 15% discount on festival season trains. Book early to avoid last-minute rush!',
        originalPrice: '₹6,000',
        discountedPrice: '₹5,100',
        progress: null
    },
    {
        id: 'train-6',
        category: 'train',
        expiry: '2025-12-31',
        popularity: 145,
        savings: 700,
        badge: 'TRAIN',
        image: '../img/img11.avif',
        title: 'Student Rail Pass',
        description: 'Special 25% discount for students on all train routes. Valid student ID required.',
        originalPrice: '₹2,800',
        discountedPrice: '₹2,100',
        progress: null
    },

    // Cab Offers (6 cards)
    {
        id: 'cab-1',
        category: 'cab',
        expiry: '2025-12-10',
        popularity: 267,
        savings: 100,
        badge: 'CAB',
        image: '../img/img12.avif',
        title: 'Car Ride Discount',
        description: 'Get flat ₹100 off on your first cab ride. Applicable in all major cities.',
        originalPrice: '₹500',
        discountedPrice: '₹400',
        progress: null
    },
    {
        id: 'cab-2',
        category: 'cab',
        expiry: '2025-11-15',
        popularity: 189,
        savings: 150,
        badge: 'CAB',
        image: '../img/img13.avif',
        title: 'Airport Transfer Special',
        description: '30% off on airport transfers. Available 24/7 with premium vehicles.',
        originalPrice: '₹500',
        discountedPrice: '₹350',
        progress: null
    },
    {
        id: 'cab-3',
        category: 'cab',
        expiry: '2025-10-31',
        popularity: 156,
        savings: 120,
        badge: 'HOT DEAL',
        image: '../img/img14.avif',
        title: 'Weekend Cab Special',
        description: '25% off on all cab rides during weekends. Explore your city in comfort and style!',
        originalPrice: '₹480',
        discountedPrice: '₹360',
        progress: null
    },
    {
        id: 'cab-4',
        category: 'cab',
        expiry: '2026-04-25',
        popularity: 134,
        savings: 200,
        badge: 'CAB',
        image: '../img/img15.avif',
        title: 'Outstation Cab Discount',
        description: '20% off on outstation cab bookings. Perfect for weekend getaways and road trips.',
        originalPrice: '₹1,000',
        discountedPrice: '₹800',
        progress: null
    },
    {
        id: 'cab-5',
        category: 'cab',
        expiry: '2026-01-30',
        popularity: 178,
        savings: 80,
        badge: 'LAST CHANCE',
        image: '../img/img16.avif',
        title: 'Ride Sharing Bonus',
        description: 'Share your ride and get 20% off. Perfect for office commutes and group travel.',
        originalPrice: '₹400',
        discountedPrice: '₹320',
        progress: null
    },
    {
        id: 'cab-6',
        category: 'cab',
        expiry: '2025-11-30',
        popularity: 145,
        savings: 100,
        badge: 'CAB',
        image: '../img/img17.avif',
        title: 'Late Night Ride Safety',
        description: 'Special 25% off on late night rides (10 PM - 6 AM). Premium verified drivers only.',
        originalPrice: '₹400',
        discountedPrice: '₹300',
        progress: null
    },

    // Package Offers (6 cards)
    {
        id: 'package-1',
        category: 'package',
        expiry: '2025-12-31',
        popularity: 223,
        savings: 5000,
        badge: 'PACKAGE',
        image: '../img/img18.avif',
        title: 'Complete Travel Package',
        description: 'Book flight + hotel together and save up to 30%. Free airport transfers included.',
        originalPrice: '₹25,000',
        discountedPrice: '₹20,000',
        progress: null
    },
    {
        id: 'package-2',
        category: 'package',
        expiry: '2025-08-28',
        popularity: 178,
        savings: 8000,
        badge: 'EXCLUSIVE',
        image: '../img/img19.avif',
        title: 'Honeymoon Special',
        description: 'Romantic getaway packages with luxury stays, candlelight dinners, and couple spa.',
        originalPrice: '₹40,000',
        discountedPrice: '₹32,000',
        progress: null
    },
    {
        id: 'package-3',
        category: 'package',
        expiry: '2025-11-15',
        popularity: 156,
        savings: 6000,
        badge: 'HOT DEAL',
        image: '../img/img18.avif',
        title: 'Family Vacation Package',
        description: 'All-inclusive family packages with activities for kids, family rooms, and meal plans.',
        originalPrice: '₹30,000',
        discountedPrice: '₹24,000',
        progress: null
    },
    {
        id: 'package-4',
        category: 'package',
        expiry: '2025-10-31',
        popularity: 189,
        savings: 4500,
        badge: 'PACKAGE',
        image: '../img/img20.avif',
        title: 'Adventure Travel Package',
        description: 'Thrilling adventure packages including trekking, camping, and outdoor activities.',
        originalPrice: '₹15,000',
        discountedPrice: '₹10,500',
        progress: null
    },
    {
        id: 'package-5',
        category: 'package',
        expiry: '2025-12-20',
        popularity: 134,
        savings: 7000,
        badge: 'PACKAGE',
        image: '../img/img18.avif',
        title: 'Luxury Cruise Package',
        description: 'Premium cruise packages with ocean view cabins, fine dining, and onboard entertainment.',
        originalPrice: '₹35,000',
        discountedPrice: '₹28,000',
        progress: null
    },
    {
        id: 'package-6',
        category: 'package',
        expiry: '2025-09-25',
        popularity: 167,
        savings: 3500,
        badge: 'LAST CHANCE',
        image: '../img/img19.avif',
        title: 'Weekend Escape Package',
        description: 'Quick weekend getaways with hotel, meals, and local sightseeing included.',
        originalPrice: '₹7,000',
        discountedPrice: '₹3,500',
        progress: null
    }
];